### ISSUE TITLE
Fix the height of 'psychological help' section in mobile view

### ISSUE THREAD

**Issue by krishna-s11** [Humble-Mental-Health/humble#5]

**Comment by rushiv7** [comment]
**You want the pink part below start now button extended right? if not can you elaborate more of the issue?**

![image](https://user-images.githubusercontent.com/39614961/116087137-2fbf5f00-a6be-11eb-84c7-e30729990238.png)

**Comment by krishna-s11** [comment]
@rushiv7 Yes right.  You just need to extend the height of the section.
Check if height's in vh(viewport height), and then change it to auto or 100% and give some padding.

**Comment by rushiv7** [comment]
**Is this okay? If yes I can raise the pull request**

![image](https://user-images.githubusercontent.com/39614961/116183946-7eabd980-a73c-11eb-9500-294a0456ea5b.png)

**Comment by krishna-s11** [comment]
@rushiv7 Yes. It’s perfect !
